import { chromium } from '@playwright/test';
const base = process.env.BASE_URL ?? 'http://localhost:5180';
const shim = (await import('./webmcp-shim.ts')).WEBMCP_SHIM;
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1360, height: 900 } });
const page = await ctx.newPage();
await page.addInitScript(shim);
await page.goto(base + '/');
await page.waitForTimeout(1500);
await page.screenshot({ path: 'docs/shots/home.png', fullPage: true });
const list = await page.evaluate(() => window.__agent.call('list_articles'));
await page.goto(base + '/a/' + list.articles[0].slug);
await page.waitForTimeout(1500);
await page.screenshot({ path: 'docs/shots/article-default.png', fullPage: false });
await page.evaluate(() => window.__agent.call('declare_reader_context', { level: 'expert', time_minutes: 3, language: 'en', knows: ['mcp'], note: 'you asked for the 3-minute expert version' }));
await page.waitForTimeout(1200);
await page.screenshot({ path: 'docs/shots/article-expert-3min.png', fullPage: true });
await page.evaluate(() => window.__agent.call('declare_reader_context', { level: 'novice', time_minutes: 0, language: 'ko' }));
await page.waitForTimeout(1200);
await page.screenshot({ path: 'docs/shots/article-novice-ko.png', fullPage: false });
await page.goto(base + '/a/' + list.articles[1].slug);
await page.waitForTimeout(1500);
const ed = await page.evaluate(() => window.__agent.call('get_edition'));
await page.evaluate(() => window.__agent.call('set_interactive', { id: 'compound-calculator', params: { monthly: 500, years: 40, fee: 1 } }));
await page.waitForTimeout(800);
const ia = page.locator('.interactive-wrap').first();
await ia.scrollIntoViewIfNeeded();
await page.waitForTimeout(600);
await page.screenshot({ path: 'docs/shots/article-interactive.png', fullPage: false });
const m = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true });
const mp = await m.newPage();
await mp.goto(base + '/a/' + list.articles[0].slug);
await mp.waitForTimeout(1500);
await mp.screenshot({ path: 'docs/shots/article-mobile.png', fullPage: false });
await browser.close();
console.log('shots done', JSON.stringify(ed.edition));
